name: s3 push
on: [pull_request]
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: up
        env:
          AWS_ACCESS_KEY_ID: \{\%\- raw \-\%\}$\{\%\- endraw \-\%\}
          AWS_SECRET_ACCESS_KEY: \{\%\- raw \-\%\}$\{\%\- endraw \-\%\}
        run: |
          # npm install
          npx @11ty/eleventy
          aws s3 cp ./_site s3://clydevalleyhorsearchers/ --recursive
